const $=id=>document.getElementById(id);
const token=location.hash.slice(1)||sessionStorage.getItem('console-token');
if(token)sessionStorage.setItem('console-token',token);
history.replaceState(null,'',location.pathname);
const stages=[['check','Check Mac setup','Verify repository, Apple Silicon, Command Line Tools, and Homebrew.','Check prerequisites'],['tools','Install required tools','Install Go, Colima, Docker, Minikube, kubectl, Helm, and helpers.','Install tools'],['cluster','Start local infrastructure','Start the project’s Colima VM and Minikube cluster.','Start cluster'],['build','Build and load images','Compile the code, build five images, and load them into Minikube.','Build and load'],['deploy','Deploy the stack','Validate Helm, bootstrap PostgreSQL, migrate, and deploy services.','Deploy'],['verify','Verify the pipeline','Check readiness, persistent storage, ingestion, acknowledgements, and API data.','Verify deployment'],['connect','Connect to the API','Start local API access, then switch to GPU Explorer.','Connect API']];
for(const [id,title,desc,label]of stages){const row=document.createElement('article');row.className='step';row.innerHTML=`<span class="number">0${stages.findIndex(s=>s[0]===id)+1}</span><div><h2>${title}</h2><p>${desc}</p><span class="status" id="status-${id}">Not run this session</span></div><button data-action="${id}">${label}</button>`;$('steps').append(row)}
async function api(path,body){const response=await fetch('/control/'+path,{method:body?'POST':'GET',headers:{'X-Console-Token':token||'','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});if(!response.ok)throw Error(await response.text());return response.status===202?null:response.json()}
function error(e){$('error').textContent=e.message}
let pendingCleanup=null;
async function submitAction(action,confirmation=''){try{$('error').textContent='';const body={action,root:$('root').value,confirmation};if(action==='deploy')for(const field of ['streamers','collectors']){const input=$(field);if(!input.checkValidity())throw Error('Replica counts must be between 1 and 10.');body[field]=Number(input.value)}await api('action',body);await refresh()}catch(e){error(e)}}
document.addEventListener('click',e=>{const action=e.target.dataset.action;if(!action)return;if(action==='cleanup'||action==='remove-environment'){pendingCleanup=action;const full=action==='remove-environment';$('cleanup-title').textContent=full?'Remove project environment?':'Clean deployment and shut down?';$('cleanup-description').textContent=full?'Remove the deployment and its data, then delete the dedicated Minikube and Colima environments, including VM images and runtime storage.':'Uninstall Helm, remove the dedicated namespace and its persisted data, verify volume removal, then stop Minikube and Colima.';$('confirmation-label').textContent='Type '+(full?'REMOVE':'DELETE')+' gpu-telemetry to confirm';$('confirmation').value='';$('confirm-cleanup').disabled=true;$('cleanup-dialog').showModal();$('confirmation').focus();return}submitAction(action)});
$('confirmation').oninput=()=>{$('confirm-cleanup').disabled=$('confirmation').value!==(pendingCleanup==='remove-environment'?'REMOVE':'DELETE')+' gpu-telemetry'};
$('dismiss-cleanup').onclick=()=>{$('cleanup-dialog').close();pendingCleanup=null};
$('confirm-cleanup').onclick=()=>{const action=pendingCleanup;const confirmation=$('confirmation').value;$('cleanup-dialog').close();pendingCleanup=null;submitAction(action,confirmation)};
$('cancel').onclick=()=>api('action',{action:'cancel'}).catch(error);
document.querySelectorAll('.tab').forEach(button=>button.onclick=()=>{document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b===button));$('deploy').hidden=button.dataset.view!=='deploy';$('explore').hidden=button.dataset.view!=='explore'});
let initial=true;
async function refresh(){try{const s=await api('status');if(initial){$('root').value=s.root;initial=false}const busy=s.phase==='running';document.querySelectorAll('[data-action]').forEach(b=>b.disabled=busy);$('root').disabled=busy;$('cancel').disabled=!busy;$('state').textContent=s.action?`${s.action} · ${s.phase}`:'Ready';const log=$('log');if(log.textContent!==s.log&&s.log){log.textContent=s.log;log.scrollTop=log.scrollHeight}for(const [id]of stages){const el=$('status-'+id);el.textContent=s.results[id]||'Not run this session';el.className='status '+(s.results[id]||'')}$('connection').textContent=s.connected?'Connected to the local API.':'API disconnected. Connect after deployment verification.';$('load').disabled=!s.connected;$('fetch').disabled=!s.connected;if(!s.connected)$('auto').checked=false}catch(e){$('state').textContent='Console unavailable. Relaunch Start Console.command if it has stopped.'}}
setInterval(refresh,1500);refresh();
