// Command openapi generates the spec from exactly the runtime route definitions, without a database.
package main

import (
	"bytes"
	"context"
	"flag"
	"fmt"
	"gpu-telemetry/internal/api"
	"gpu-telemetry/internal/config"
	"io"
	"log/slog"
	"os"
)

func run() error {
	check := flag.Bool("check", false, "compare generated bytes with the existing specification; do not modify it")
	output := flag.String("output", "api/openapi.yaml", "generated specification path")
	flag.Parse()
	if flag.NArg() != 0 {
		return fmt.Errorf("unexpected arguments")
	}
	_, a := api.New(context.Background(), nil, config.DefaultAPI(), slog.New(slog.NewJSONHandler(io.Discard, nil)))
	b, err := a.OpenAPI().YAML()
	if err != nil {
		return err
	}
	if *check {
		old, err := os.ReadFile(*output)
		if err != nil {
			return err
		}
		if !bytes.Equal(old, b) {
			return fmt.Errorf("OpenAPI is stale; run make openapi")
		}
		fmt.Println("OpenAPI is current")
		return nil
	}
	return os.WriteFile(*output, b, 0644)
}
func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
